### ISSUE TITLE
на странице все новости убрать картинки

### ISSUE THREAD

**Issue by EugeneKormin** [simlex-titul2005/game-exe.com#10]

**Comment by simlex-titul2005** [comment]
А чем это вызвано?

**Comment by EugeneKormin** [comment]
они одни и те же. Хотя, можно оставить

**Comment by simlex-titul2005** [comment]
К новости, как модели БД прикреплена картинка. Для новостей, у которых картинки нет, можно прицепить какую-нибудь по-умолчанию. Без картинок - обработать в html согласно общего дизайна.
