### ISSUE TITLE
Добавить возможность добавления и изменения категорий для каждой игры независимо друг от друга в блоке геймеру почитать

### ISSUE THREAD

**Issue by EugeneKormin** [simlex-titul2005/game-exe.com#11]
![image](https://cloud.githubusercontent.com/assets/16157678/12349002/3f93b5fa-bbc0-11e5-929d-941c475ad68c.png)

**Comment by simlex-titul2005** [comment]
Куда будут вести ссылки с этих групп?

**Comment by EugeneKormin** [comment]
это будут такие же группы как положительные, отрицательные, гайды... (good, bad, guide)

**Comment by simlex-titul2005** [comment]
Понял. Т.е. Для каждой игры должен быть свой список групп. Давай называть их категориями. Для новостей, конкурсов, тем форума они нужны?

**Comment by EugeneKormin** [comment]
давай, нет, пока только для статей

**Comment by simlex-titul2005** [comment]
Сделал
