### ISSUE TITLE
Убрать "-img" из из тега h1

### ISSUE THREAD

**Issue by EugeneKormin** [simlex-titul2005/game-exe.com#14]
http://audit.megaindex.ru/audit/site_meta/h1/game-exe.com?field=error&sort=desc

пример:
страница: "http://game-exe.com/articles/details/neskolko-sposobov-podnyat-fps-v-varfeys-kak-izbavitsya-ot-lagov-i-nachat-igrat" 

тег h1:
"~img~ 
Несколько способов поднять FPS в Варфейс: как избавиться от лагов и начать играть"

**Comment by simlex-titul2005** [comment]
сделал
