### ISSUE TITLE
добавить возможность добавлять мета-теги для каждой страницы сайта

### ISSUE THREAD

**Issue by EugeneKormin** [simlex-titul2005/game-exe.com#15]
обновить страницу http://game-exe.com/admin/seo/edit

чтобы можно было добавлять метатеги:

title
keywords
description
h1 (h2, h3... если необходимо)

**Comment by simlex-titul2005** [comment]
H1,h2 и пр. Нельзя - это разметка

**Comment by EugeneKormin** [comment]
тогда, все кроме, h1, h2, h3...
