### ISSUE TITLE
Тег Title

### ISSUE THREAD

**Issue by simlex-titul2005** [simlex-titul2005/game-exe.com#16]
Описать правила формирования тега. Я его вынес в отдельный класс. Для разных страниц... Что там должно быть, какой разделитель и по.

**Comment by EugeneKormin** [comment]
Все метатеги пишутся руками, или я не понял вопрос.

**Comment by simlex-titul2005** [comment]
Ситуация такая. Будет возможность изменить Title для любой страницы. НО Title также формируется для материалов динамически (Главная - > Статьи -> Статья№1). Вот при таком раскладе лучше задать алгоритм формирования тега.

**Comment by EugeneKormin** [comment]
наиболее часто встречающаяся на странице фраза. Но проверяться она все-равно должна руками. Сайт должен спрашивать "вас устраивают эти слова и фразы в качестве тегов?".

**Comment by simlex-titul2005** [comment]
формируется искуственно
