### ISSUE TITLE
Исправление блока "Новости" (неверно раскрываются блоки с играми)

### ISSUE THREAD

**Issue by EugeneKormin** [simlex-titul2005/game-exe.com#22]
1) После того, как пользователь уберет мышь с блока новости вкладка с игрой должна свернуться и снова должно появится 4 "столбика" с новостями по играм как при перезагрузке сайта.

**Comment by simlex-titul2005** [comment]
Там баг с отображением фоток игры. В новом все норм...

**Comment by EugeneKormin** [comment]
ок

**Comment by simlex-titul2005** [comment]
Пока не закрывай, плиз, после заливки нового все перезакроем...

**Comment by EugeneKormin** [comment]
ок

**Comment by simlex-titul2005** [comment]
Готово

**Comment by EugeneKormin** [comment]
У меня все-равно не работает
![123](https://cloud.githubusercontent.com/assets/16157678/13653705/fd428e1a-e69e-11e5-897d-f1f58ee55fe9.png)
