### ISSUE TITLE
Добавить кнопку для возвращения на главную перед и после статьи и новости

### ISSUE THREAD

**Issue by EugeneKormin** [simlex-titul2005/game-exe.com#23]
Перед текстом (новостью или статьей) добавить 2 кнопки обе должны вести на главную, но на одной надпись "Это интересно, что тут есть ещё?", на другой "Это не то, что я искал, попробую снова".

**Comment by EugeneKormin** [comment]
Сразу не написал, нужно считать куда нажмёт пользователь для каждой статьи

**Comment by simlex-titul2005** [comment]
Сделал
