### ISSUE TITLE
Тег Keywords

### ISSUE THREAD

**Issue by EugeneKormin** [simlex-titul2005/game-exe.com#30]
Добавить тег keywords в таблицу к тегам desription и title. Вроде, его вес небольшой, но алгоритмы меняются чуть ли не ежемесячно, поэтому лучше, чтоб было. Да и для внутренней оптимизации полезно.

**Comment by simlex-titul2005** [comment]
Тег можно формировать для любой страницы здесь: http://admin-game-exe.azurewebsites.net/seoinfo

**Comment by EugeneKormin** [comment]
А как добавлять тег Keywords?

**Comment by simlex-titul2005** [comment]
http://admin-game-exe.azurewebsites.net/seoinfo/edit?Id=2
Ключевые слова - добавить

**Comment by simlex-titul2005** [comment]
Сделал
