### ISSUE TITLE
Добавить фон

### ISSUE THREAD

**Issue by EugeneKormin** [simlex-titul2005/game-exe.com#6]
Сейчас отрисовывается

**Comment by EugeneKormin** [comment]
![image](https://cloud.githubusercontent.com/assets/16157678/13543064/26a0a5d2-e2ab-11e5-85d6-b5352f4d13e5.jpeg)
![image](https://cloud.githubusercontent.com/assets/16157678/13543065/26d6acea-e2ab-11e5-8ed0-c460688059b8.jpeg)
![image](https://cloud.githubusercontent.com/assets/16157678/13543066/26ffe9f2-e2ab-11e5-8788-38c080c40054.jpeg)
![image](https://cloud.githubusercontent.com/assets/16157678/13543067/2703e14c-e2ab-11e5-9587-c956259df19f.jpeg)
![image](https://cloud.githubusercontent.com/assets/16157678/13543068/27060288-e2ab-11e5-9c94-cec31c6105a2.jpeg)
![image](https://cloud.githubusercontent.com/assets/16157678/13543069/270ac354-e2ab-11e5-8cae-a475bf144d5b.jpeg)
![image](https://cloud.githubusercontent.com/assets/16157678/13543070/27368c28-e2ab-11e5-95d2-283bb30356a9.jpeg)
![image](https://cloud.githubusercontent.com/assets/16157678/13543071/273e7316-e2ab-11e5-9289-6fd5293822fc.jpeg)
![image](https://cloud.githubusercontent.com/assets/16157678/13543072/2742ba5c-e2ab-11e5-84f1-7270095742d0.jpeg)

**Comment by EugeneKormin** [comment]
В  качестве примера можно использовать любой понравившийся, сейчас главное потестить саму возможность установки и смены фона

**Comment by simlex-titul2005** [comment]
реализовано
